language: node_js

dist: trusty

cache:
  directories:
    - ~/.npm

node_js:
  - '11'

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then DEV_TO_GIT_TOKEN=$DEV_TO_GIT_TOKEN yarn run dev-to-git; fi

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
